config/routes.rb
Rails.application.routes.draw do
  get 'settings/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions
  root to: redirect('sessions/new')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'sessions/show'
  post 'sessions/createSession'
  post 'sessions/joinSession'

  resources :cards
  get :deckoverview, controller: :cards
  root to: redirect('/cards')

  resources :users
  get 'users/show'
  get :user_hand, controller: :users
  post 'users/draw'
  post 'cards/deal_all'
  post 'users/update'
  post 'users/increment_score'
  post 'users/decrement_score'

  resources :settings
  post 'settings/index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :account_id, uniqueness: true
  def self.from_omniauth(auth)
    where(provider: auth[:provider], uid: auth[:uid]).first_or_initialize.tap do |user|
      user.provider = auth[:provider]
      user.uid = auth[:uid]
      user.account_id = rand(10 ** 8)
      user.name = auth[:info][:name]
      user.email = auth[:info][:email]
      user.session_token = SecureRandom.base64
      user.save!
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def user_hand
    @hand_cards = Card.where(pile_id: current_user.account_id).sort_by{ |card| card[:card_suit] }
    @active_user = User.where(active_session: current_user.active_session)
    @list = []
    @active_user.each do |player|
      @list << player.account_id
    end
    @visible_cards = Card.where(visible: true).where(pile_id: @list).sort_by{|card| card[:pile_id]}
    pile_ids=[]
    @visible_cards.each do |card|
      pile_ids.append(card[:pile_id])
    end
    @visible_users=User.where(account_id: pile_ids)
    render partial: "user_hand"
  end

  def show
    if current_user == nil
      redirect_to cards_path, notice: "You are not logged in, Must log in to view your cards"
    else
      @session_id = Settings.find_by_uid(current_user.uid)
      @current_user_score = Score.find_by(email: current_user.email)
    end
  end

  def draw
    cards = Card.where(pile_id: current_user.active_session)
    card = cards[rand(cards.length)]
    if card.nil?
      flash[:notice] = 'No card available in the deck'
    else
      card.update(pile_id: current_user.account_id)
      flash[:notice] = "You got #{card.card_value} of #{card.card_suit}"
    end
    #redirect_to users_show_path
  end

  def update
    if params[:commit] == "Discard"
      discard
    elsif params[:commit] == "Send"
      if params[:player_id].empty?
        flash[:notice] = 'Select a player'
        #redirect_to users_show_path
      else
        player = params[:player_id].to_i
        send_to_player(player)
      end
    elsif params[:commit] == "Toggle Visibility"
      makeVisible
    end
  end

  def makeVisible
    if params[:selected_card].present?
      params[:selected_card].keys.each do |card|
        selected_card = Card.find_by_id(card)
        if selected_card[:visible]
          selected_card.update(visible: false)
        else
          selected_card.update(visible: true)
        end
      end
      flash[:notice] = 'Card made Visible!'
    else
      flash[:notice] = 'No card selected'
    end
  end

  def discard
    if params[:selected_card].present?
      params[:selected_card].keys.each do |card|
        selected_card = Card.find_by_id(card)
        selected_card.update(pile_id: 1000000 + current_user.active_session)
        if selected_card[:visible]
          selected_card.update(visible: false)
        end
      end
      flash[:notice] = 'Card discarded successfully!'
    else
      flash[:notice] = 'No card selected'
    end
    #redirect_to users_show_path
  end

  def send_to_player(player)
    if params[:selected_card].present?
      params[:selected_card].keys.each do |card|
        selected_card = Card.find_by_id(card)
        selected_card.update(pile_id: player)
      end
      user = User.find_by_account_id(player)
      flash[:notice] = "Card sent to #{user[:name]} successfully!"
    else
      flash[:notice] = 'No card selected'
    end
    #redirect_to users_show_path
  end

  def increment_score
    if current_user == nil
      flash[:notice] = "You are not logged in, Must log in to view your cards"
    else
      if Score.exists?(email: current_user.email)
        score_update = Score.find_by(email: current_user.email)
        score = score_update[:score]
        score += 10
        score_update.update(score: score)
      end
    end
    #redirect_to users_show_path
  end

  def decrement_score
    if Score.exists?(email: current_user.email)
      score_update = Score.find_by(email: current_user.email)
      score = score_update[:score]
      score -= 10
      if score.negative?
        score = 0
        flash[:warning] = "Score can not be decremented anymore!\n"
      end
      score_update.update(score: score)
    end
    #redirect_to users_show_path
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_hand.html.erb
<div class="row rounded border border-dark" style="margin-bottom: 15px; background-color: #b8b7b7; padding: 20px">

  <div class="col-6">
    <h4>Game Stats:</h4>
    <div class="row">
      <p class="col-6">Number of TOTAL players:</p>
      <p class="col-6"><%= User.where(active_session: current_user.active_session).count%></p>
    </div>
    <% User.where(active_session: current_user.active_session).each do |user| %>
      <div class="row">
        <div class="col-6"> <%= user.name + "'s Number of Cards:" %></div>
        <div class="col-6"> <%= Card.where(pile_id: user.account_id).count %></div>
      </div>
    <% end %>
  </div>
  <div class="col-6" style="padding-top: 15px;">
    <h5> Scoreboard: </h5>
    <% User.where(active_session: current_user.active_session).each do |user| %>
      <div class="row">
        <div class="col-6"> <%= user.name %> </div>
        <div class="col-6"> <%= Score.find_by(email: user.email)[:score] %></div>
      </div>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-6">
    <%= button_to 'Draw Card', users_draw_path, class: 'btn' %>
    <%= form_with url: users_update_path do |f| %>
      <table class="table-of-cards rounded">
        <thead>
        <tr>
          <th style="padding: 15px">List of Your Cards</th>
        </tr>
        </thead>
        <tbody>
        <% if @hand_cards != nil %>
          <% @hand_cards.each do |card| %>
            <tr>
              <td style="padding-left: 15px; padding-bottom: 15px;">
                <%= image_tag(card[:card_value].to_s + '_' + card[:card_suit] + '.png', width: 100, height: 150) %>
                <%#= card[:card_value] + ' of ' + card[:card_suit] %>
              </td>
              <td style="padding-right: 15px; padding-bottom: 15px;">
                <%= check_box_tag("selected_card[#{card[:id]}]", "1", false, class: 'checkbox') %>
              </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>

      <h4>Choose which action to take with selected cards:</h4>
      <%= f.submit "Discard", class: 'btn' %>
      <%= f.submit "Toggle Visibility", class: 'btn' %>
      <h6 style="padding-top: 15px"> -- OR -- </h6>
      <div>
        <label> Send selected cards to: </label>
        <%= f.select :player_id, User.where.not(account_id: current_user.account_id).where(active_session: current_user.active_session).collect{ |p| [p.name, p.account_id]}, include_blank: true %>
        <%= f.submit "Send", class: 'btn' %>
      </div>
    <% end  %>
  </div>
  <div class="col-6">
    <table class="table-of-cards rounded">
      <thead>
      <tr>
        <th style="padding: 15px">List of Visible Cards</th>
      </tr>
      </thead>
      <tbody>
      <% if @visible_cards != nil %>
        <% @visible_cards.each do |card| %>
          <tr>
            <td style="padding-left: 15px; padding-bottom: 15px;">
              <%= @visible_users.where(account_id: card[:pile_id]).pluck(:name)%>
            </td>
            <td style="padding-left: 15px; padding-bottom: 15px;">
              <%= image_tag(card[:card_value].to_s + '_' + card[:card_suit] + '.png', width: 100, height: 150) %>
              <%#= card[:card_value] + ' of ' + card[:card_suit] %>
            </td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>

  </div>
</div>

<hr>

<div class="text-center">
  <% if @current_user %>
    <%= button_to 'Add 10 to Your Score', users_increment_score_path, class: 'btn col-2'%>
    <%#= @current_user_score[:score] %>
    <%= button_to 'Subtract 10 from Your Score', users_decrement_score_path, class: 'btn col-2' %>
  <% end %>
</div>
<hr>

app/views/users/show.html.erb
<div class="container">
  <div class="sticky-top border border-dark rounded col-12" style="background-color: white; padding: 25px;">
  <div class="row col-12 text-center">
    <h1>Player Center</h1>
  </div>
  <hr>
  <div class="row align-middle">
    <div class="col-6"><input type="button" id="perform-turn" value="PERFORM TURN" class="btn col-6" style="height: 100%; font-weight: bolder"/></div>
    <div class="col-6 text-right">
      <% if @current_user %>
        Signed in as <%= @current_user.name %>
        <%= link_to 'Sign Out', signout_path, class: 'btn' %>
      <% end %>
      <div>
        <label>Session Code: </label>
        <%= current_user[:active_session] %>
      </div>
    </div>
  </div>
  </div>
  <% if flash[:notice] %>
    <div class="flash-message text-center rounded">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <br>
  <%= render_async user_hand_path, toggle: { selector: '#perform-turn', event: :click, start:true}, interval: 2000%>

  <div class="row">
    <%= link_to 'Return to Decks', cards_path, class: 'btn' %>
  </div>

</div>


<script>
    var turnButton = document.getElementById('perform-turn')
    turnButton.addEventListener('click', function() {
        if (turnButton.value === 'PERFORM TURN') {turnButton.value = 'DONE WITH TURN'}
        else {turnButton.value = "PERFORM TURN"}
    })
</script>