config/routes.rb
Rails.application.routes.draw do
  get 'settings/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions
  root to: redirect('sessions/new')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'sessions/show'
  post 'sessions/createSession'
  post 'sessions/joinSession'

  resources :cards
  get :deckoverview, controller: :cards
  root to: redirect('/cards')

  resources :users
  get 'users/show'
  get :user_hand, controller: :users
  post 'users/draw'
  post 'cards/deal_all'
  post 'users/update'
  post 'users/increment_score'
  post 'users/decrement_score'

  resources :settings
  post 'settings/index'

end

app/models/card.rb
class Card < ActiveRecord::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def deckoverview
    render partial: "deckoverview"
  end

  def index
    @cards = Card.where(pile_id: current_user.active_session)
    @discard_card = Card.where(pile_id: 1000000 + current_user.active_session)
  end

  def deal_all
    users = User.where(active_session: current_user.active_session)
    dealnum = Integer(params[:num_cards])
    deck = Card.where(pile_id: current_user.active_session)
    if deck.length == 0
      redirect_to users_show_path, notice: 'No cards available to deal in deck'
    else
      # loops through each user
      users.each do |user|
        # loops through the requested number of cards
        i = 0
        while i < dealnum do
          # gets the most updated form of the deck
          deck = Card.where(pile_id: current_user.active_session)
          # gets a random card
          if deck.length == 0
            flash[:notice] = "The deck ran out of cards"
            break
          end
          card = deck[rand(deck.length)]
          # puts that random card in the current user's hand
          card.update(pile_id: user.account_id)
          # increments loop counter
          i = i + 1
        end
        # end
        flash[:notice] = "You dealt cards"
      end
      redirect_to users_show_path
    end

  end


end

app/views/cards/_deckoverview.html.erb
<div class="row">
  <div class="col-5 border border-black rounded" style="padding: 15px; margin-right:10px;">
    <h5>Number of Draw Deck Cards:</h5>
  </div>
  <div class="col-5 border border-black rounded" style="padding: 15px; margin-left: 10px;">
    <h5>Number of Discard Deck Cards:</h5>
  </div>
</div>

app/views/cards/index.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="flash-message text-center rounded">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="row text-center"> <h1>Deck Overview</h1> </div>

  <hr>

  <div class="row">
    <div class="col-6">
      <div>
        <%= form_tag cards_deal_all_path, method: :post do %>
          <%= label :num_cards, 'Number of Cards To Deal to All Players' %>
          <%= text_field_tag :num_cards, params[:num_cards] %>
          <%= submit_tag "Deal Cards", name: cards_deal_all_path, class: 'btn' %>
        <% end %>
      </div>
      <button type="button" class="btn" id="refresh" onClick="refreshPage()">Refresh Decks</button>
    </div>

    <div class="col-6 text-right">
      <div style="padding-bottom: 15px;">
      <%= button_to 'My Card', users_show_path, method: :get, class: 'btn'%>
      </div>
      <div>
        <% if current_user %>
          Signed in as <%= current_user.name %>
          <%= link_to 'Sign Out', signout_path, class: 'btn' %>
        <% else %>
          <%= link_to 'sign in', root_path %>
        <% end %>
      </div>

    </div>

  </div>

  <hr>


    <div class="row">
      <div class="col-5 border border-black rounded" style="padding: 15px; margin-right:10px;">
        <h5>Number of Draw Deck Cards:</h5>
        <%= Card.where(pile_id: current_user.active_session).count %>
      </div>
      <div class="col-5 border border-black rounded" style="padding: 15px; margin-left: 10px;">
        <h5>Number of Discard Deck Cards:</h5>
        <%= Card.where(pile_id: 1000000 + current_user.active_session).count %>
      </div>
    </div>

</div>

<script>

  function refreshPage() {
      window.location.reload();
  }

</script>